/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/SetttingsContext`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useSettings`; params?: Router.UnknownInputParams; } | { pathname: `/../components/days/DaysList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/days/DayItem`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/DateContext`; params?: Router.UnknownInputParams; } | { pathname: `/../components/chart/chart`; params?: Router.UnknownInputParams; } | { pathname: `/../components/days/days.types`; params?: Router.UnknownInputParams; } | { pathname: `/../components/days/days.styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/../contexts/SetttingsContext`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useSettings`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/days/DaysList`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/days/DayItem`; params?: Router.UnknownOutputParams; } | { pathname: `/../contexts/DateContext`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/chart/chart`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/days/days.types`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/days/days.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/../contexts/SetttingsContext${`?${string}` | `#${string}` | ''}` | `/../hooks/useSettings${`?${string}` | `#${string}` | ''}` | `/../components/days/DaysList${`?${string}` | `#${string}` | ''}` | `/../components/days/DayItem${`?${string}` | `#${string}` | ''}` | `/../contexts/DateContext${`?${string}` | `#${string}` | ''}` | `/../components/chart/chart${`?${string}` | `#${string}` | ''}` | `/../components/days/days.types${`?${string}` | `#${string}` | ''}` | `/../components/days/days.styles${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/SetttingsContext`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useSettings`; params?: Router.UnknownInputParams; } | { pathname: `/../components/days/DaysList`; params?: Router.UnknownInputParams; } | { pathname: `/../components/days/DayItem`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/DateContext`; params?: Router.UnknownInputParams; } | { pathname: `/../components/chart/chart`; params?: Router.UnknownInputParams; } | { pathname: `/../components/days/days.types`; params?: Router.UnknownInputParams; } | { pathname: `/../components/days/days.styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
